export const PROFESSION_SUGGESTIONS: string[] = [
  "Software Engineer",
  "Data Scientist",
  "Product Manager",
  "UI/UX Designer",
  "Graphic Designer",
  "Digital Marketer",
  "Content Creator",
  "Entrepreneur / Founder",
  "Business Analyst",
  "Financial Analyst",
  "Accountant",
  "Lawyer",
  "Doctor",
  "Nurse",
  "Psychologist",
  "Researcher / Academic",
  "Lecturer / Dosen",
  "Teacher / Guru",
  "Student / Mahasiswa",
  "Architect",
  "Civil Engineer",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Consultant",
  "Project Manager",
  "Sales Executive",
  "Customer Success",
  "Human Resources",
  "Photographer",
  "Videographer",
  "Musician / Artist",
  "Writer / Journalist",
  "Chef / Culinary",
  "Pilot / Aviation",
  "Military / Police",
  "Civil Servant / PNS",
  "Banker",
  "Trader / Investor",
  "Freelancer",
  "Homemaker",
  "Retired",
  "Other",
];
